### ISSUE TITLE
Awesome Work! Can I Collaborate on This Project?

### ISSUE THREAD

**Issue by leduy-it** [tungedng2710/license-plate-recognition#4]
It's rare to come across public projects shared with the community in Vietnamese, and it's truly inspiring to see your dedication to open-source development. I genuinely admire your work and would love to contribute to this project. Please let me know how I can get involved or collaborate further. Feel free to reach out to me! Looking forward to connecting!
Contact me via: levduyit@gmail.com

**Comment by tungedng2710** [comment]
I have added you to this project and await your response

**Comment by leduy-it** [comment]
Thank you for the invitation! Firstly, I would like to propose modifying the recognition model to use a more streamlined vocabulary, as the current 6000+ vocab seems excessive and unnecessary for this specific task. Additionally, the accuracy of the public PPOCRv4 model for Latin characters and numbers is not optimal compared to a model trained specifically for this task.
